### ISSUE TITLE
Dependency on now-outdated APC cache

### ISSUE THREAD

**Issue by andrewandante** [silverstripeltd/frisp#25]
https://github.com/silverstripeltd/frisp/blob/master/Frisp/Reader.php#L21-L28

Logs a notice if APC is not installed - which is the case with >PHP7. This means we can't read from the vault nicely (the notice obscures the actual return value) and deployments fail.

I've added APCU into our baseboxes to restore functionality, but this should be replaced with `memcached` or `opcache` probably.

**Comment by dhensby** [comment]
`APCu` is still maintained, so should be an acceptable replacement.

`OPcache` seems to be purely for op code caching of php files, so can't be used as a replacement. `memcached` could be used but if you're thinking about various backends, then maybe implementing a PSR-6 cache library would be better..

**Comment by halkyon** [comment]
Not a problem, as it uses `APCu`, it just looks like the caching library is using `APC` (without the U)
